name: segment_display
description: Segment display widget for Flutter. Supports multiple types of segment displays and segment customization.
version: 0.2.0
author: Jan Å tol <honzastol@gmail.com>
homepage: https://github.com/janstol/flutter_segment_display
repository: https://github.com/janstol/flutter_segment_display

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.5.0

flutter:
